### ISSUE TITLE
Bug in TableLayout

### ISSUE THREAD

**Issue by aviaryan** [aviaryan/Hinix#1]
The TableLayout used in the game play screen shows extra margins at both the right and bottom side. This eats a lot of space. However, if the margins are removed, some part of table gets trimmed. We don't know the cause of this issue. A fix will be highly appreciated.

**Comment by wadleo** [comment]
Hey, I have fixed this issue, will be sending a pull request shortly.

**Comment by wadleo** [comment]
Hi @aviaryan, I also created a branch for the fix of this bug #1 . Hope it reduces the space from the right and bottom margins.
