### ISSUE TITLE
Undo button conflicts

### ISSUE THREAD

**Issue by RajuKoushik** [aviaryan/Hinix#15]
Minor algorithmic glitches of the Undo function have to be implemented and fixed.

**Comment by saurabhjn76** [comment]
minor changes required.

**Comment by wadleo** [comment]
@saurabhjn76 can you highlight some of the minor changes.

**Comment by aviaryan** [comment]
@wadleo Undo button issues have been fixed now in PR #38.  Hence this issue is not needed.
