### ISSUE TITLE
Implementing functions in the MainActivity

### ISSUE THREAD

**Issue by RajuKoushik** [aviaryan/Hinix#16]
Functions have to be implemented in the MainActivity , for making it modular and to improve redundancy.

**Comment by wadleo** [comment]
Hey, can I work on this?

**Comment by RajuKoushik** [comment]
@wadleo  Before working on it, can you give us a clearer prospective of how you are going to deal with this.

**Comment by wadleo** [comment]
Methods such as the isWord(),  find2Words() and find2WordsUtil need to be in the main activity (and others too) to make the app modular. Also, more help from anyone is appreciated.

**Comment by RajuKoushik** [comment]
You can go with it. @wadleo

**Comment by aviaryan** [comment]
@wadleo I think they are right where they are.. All those methods are part of the GameBoard. 
MainActivity should be responsible for using the gameBoard object and using its methods to facilitate the gameplay. It is doing that right but there are a lot of if..else conditions in MainActivity for handling cases and such. They need to be optimized.

**Comment by wadleo** [comment]
Ok, I will also look in to that. Can anyone @RajuKoushik @aviaryan, state some of the features of this game will or should have in the future. I think this can direct us more towards this issue.

**Comment by aviaryan** [comment]
Hey @wadleo . Thanks for your interest in our project. Unfortunately we think that this issue's objectives are not clear and so this will be closed. It would be great if you can work on other issues.

**Comment by wadleo** [comment]
:+1:
