### ISSUE TITLE
Make a separate activity to show computer words

### ISSUE THREAD

**Issue by aviaryan** [aviaryan/Hinix#4]
A separate activity to show the words formed by computer is needed. It will only display the words that were not formed by the user. It can use some animation on the board to show how the words are being formed. The GameBoard class already has a property `computerSteps` which contains moves for each word formed by computer.

**Comment by wolframtheta** [comment]
Can I do this?

**Comment by aviaryan** [comment]
Sure @wolframtheta . But before that, please have a look into the [codebase](https://github.com/aviaryan/Hinix/blob/neo-reborn/app/src/main/java/in/aviaryan/hinix/GameBoard.java) and see how the `computerSteps` variable is populated. It is responsible for storing a map of word v/s [the steps] that computer took to make that word. You will have to create an activity having the game board (similar to the current gameplay activity) and animate the steps there. A button should be added to that layout which will animate the formation of words formed by the computer, one word at the time.

**Comment by wolframtheta** [comment]
Okey @aviaryan today I have a look it and I hope i will do it fine.

**Comment by wadleo** [comment]
hey @wolframtheta are you still working on this?

**Comment by wolframtheta** [comment]
Yes, but I don't finish it yet @wadleo

**Comment by wadleo** [comment]
Ok

**Comment by wadleo** [comment]
@wolframtheta, I would love to enquire how far you have gone with this task. I suggest if you are facing any difficulty, you can ask here, thanks. Just trying to be of help.

**Comment by wolframtheta** [comment]
I don't know why but Java 8 was removed from my computer and I'm trying to put it... but it's impossible... so I think until Tuesday it won't be repaired that. If @wadleo wants to do it before Tuesday go ahead.

**Comment by aviaryan** [comment]
Closing as it is no longer desired. We are displaying the computer word list in an AlertDialog and that seems to be sufficient for now. I don't think this will ever be needed. Thank you @wolframtheta and @wadleo for your interest.
