### ISSUE TITLE
Remove undo button and make undo on touch

### ISSUE THREAD

**Issue by aviaryan** [aviaryan/Hinix#40]
Re-touching or re-clicking a cell will undo selecting it. Ofcourse it will have to be the last selected cell by the user for it to be undo'ed else no action will be taken. 

@saurabhjn76 views ?

**Comment by wadleo** [comment]
Hey @aviaryan, I think both ways should be available. Let me look in to this will sent a pull request shortly, thanks.

**Comment by wadleo** [comment]
Hi, @aviaryan made it possible to undo by retouching the same latest tile. Also, as I proposed, both ways are necessary cause some users might not realised that. Also we can remove the button if we have something better to do there (suggestions). This is the PR #46

**Comment by aviaryan** [comment]
@wadleo Thanks. Neat work.
