### ISSUE TITLE
Reduce codacy issues

### ISSUE THREAD

**Issue by aviaryan** [aviaryan/Hinix#41]
Codacy reports can be seen here. 
https://www.codacy.com/app/aviaryan/Hinix/issues

**Comment by wadleo** [comment]
Hi, @aviaryan I would love to give a hand at this?

**Comment by aviaryan** [comment]
@wadleo Sure. Please have a look at the reports and try to minimize the issues. Once done, send a PR.

**Comment by wadleo** [comment]
Ok, I'm on it.

**Comment by aviaryan** [comment]
@wadleo please try to make sure that you don't commit files inside .idea/ folders in the PR . Only *.java files should be committed and be updated in the PR.

**Comment by wadleo** [comment]
Ok @aviaryan I created a branch to solve this #43 . Hope these changes improve the code.
