### ISSUE TITLE
Remove unnecessary xml layout files.

### ISSUE THREAD

**Issue by nileshchat** [aviaryan/Hinix#47]

**Comment by wadleo** [comment]
Hi @Nilesh4145, this task was part of suggestions by codacy, but I didn't remove them cause I thought  the maybe used later or for reference. But if these files (both layout and drawable files) are no longer useful, then I think I should just removed them and add that to #43

**Comment by aviaryan** [comment]
@Nilesh4145 @wadleo Which xml is not needed ?

**Comment by nileshchat** [comment]
@aviaryan the renamed ones, with suffix 1 and 2. I've done it btw...
