### ISSUE TITLE
Show a Loading dialog 

### ISSUE THREAD

**Issue by aviaryan** [aviaryan/Hinix#49]
Show a loading dialog / popup when user clicks on Play. This is because generating a larger grid can take some amount of time.

**Comment by nileshchat** [comment]
Done!

**Comment by Rishabhk07** [comment]
hey , can i pick up this issue ?

**Comment by aviaryan** [comment]
@Rishabhk07 
Nilesh has done this issue, he just needs to send the PR.

**Comment by nileshchat** [comment]
@aviaryan I've sent the PR.
