### ISSUE TITLE
Improve Loading dialog

### ISSUE THREAD

**Issue by aviaryan** [aviaryan/Hinix#55]
The loading dialog shown when the user presses on Play on that start screen shows no animation. Right now, it just has the text "Loading" . Please show a revolving circle or similar animation there. 
The aim of this issue is that the loading dialog becomes consistent with the current standards.

**Comment by shivamarora96** [comment]
can i solve this issue ? --> Improve Loading dialog #55

**Comment by rohanagarwal94** [comment]
@aviaryan I would like to work on this.

**Comment by aviaryan** [comment]
@rohanagarwal94 Thanks for your interest. Since @shivamarora96 asked first to work on this issue, it would be better if he starts to work on it.

**Comment by shivamarora96** [comment]
Done Improved the Loading Dialog @aviaryan

**Comment by aviaryan** [comment]
Thanks @shivamarora96 :smile:
