### ISSUE TITLE
Update the words database to improve results...

### ISSUE THREAD

**Issue by nileshchat** [aviaryan/Hinix#56]
Does not take some simple words..word list needs update..

**Comment by wadleo** [comment]
@Nilesh4145 pls can you expantiate more on this. Should more words be added or changed, ...

**Comment by nileshchat** [comment]
@wadleo  For now, the word list contains more archaic(old) words, and misses out some of the more common words, that needs to be fixed.

**Comment by aviaryan** [comment]
One optimization that can be done to compact the word list is to remove all words < 4 in length. Will do it when I get time

**Comment by aviaryan** [comment]
IDEA: Since wordlist can be large, it's better if the board is solved irrespective of that. 
Board can be traversed in all possible combinations and words formed which are not prefix of anything can be removed instantly. (using sorted word list and binary search)
