### ISSUE TITLE
Move "Show words" button to top and show list of words in separate activity

### ISSUE THREAD

**Issue by aviaryan** [aviaryan/Hinix#60]
<strike>Game should end</strike> when user click on "show words" and a new activity should be launched with the list of words. <strike>When the user goes back from that activity, they should go to the start screen and not the game. </strike>
Also "Show words" button can be moved to the top right side of the screen in the form of the icon. 
This will help us in removing the scroll bar in the future.

**Comment by aviaryan** [comment]
Update: Game should not end on clicking "Show words"

**Comment by nileshchat** [comment]
Done!

**Comment by aviaryan** [comment]
Fixed by #72
