### ISSUE TITLE
Add icons in Gameplay activity

### ISSUE THREAD

**Issue by aviaryan** [aviaryan/Hinix#7]
Colourful icons can be added for labels like "Current score" and "max score".

**Comment by teajason** [comment]
Hello, I'd like to contribute!

**Comment by RajuKoushik** [comment]
@teajason Sure.

**Comment by teajason** [comment]
Hey, I added this comment to the wrong issue; my apologies. I'm not an artist but I could certainly find random icons to add. Unless there are icons you had in mind?

**Comment by aviaryan** [comment]
@teajason We don't have anything specific in mind. Anything that fits in the context would do.
