### ISSUE TITLE
Reduce min sdk version

### ISSUE THREAD

**Issue by aviaryan** [aviaryan/Hinix#74]
Currenty min sdk version is set to 21 meaning Lollipop. I think the version can be further reduced without issues and this will in turn help us support more devices. 
What do you think? 
@saurabhjn76 @Nilesh4145 @RajuKoushik

**Comment by wadleo** [comment]
Yeah, I think that's true and will increase the number of people who can install the app.

**Comment by RajuKoushik** [comment]
That's true, we have to reduce the min sdk version so that it is accessible to more number of people.

**Comment by karanjuneja1106** [comment]
Can i fix this issue??

**Comment by wadleo** [comment]
Ok @karajuneja1106

**Comment by aviaryan** [comment]
Ok. Go ahead @karanjuneja1106 . Be sure to test the app on the lower sdk version before sending a PR.

**Comment by nileshchat** [comment]
yea...sure...i think reducing the minimum sdk version to 19 would be enough to cover a wider of the devices.
