### ISSUE TITLE
Gameplay issue

### ISSUE THREAD

**Issue by Monal5031** [aviaryan/Hinix#89]
There is a issue with deactivating letters.
Like for a word e.g. `abvolt`, there is specifically only one a which I can select to spell this word even if we have multiple options for choosing `a`, Uploaded screenshot too.
![screenshot_2017-06-03-19-22-34](https://cloud.githubusercontent.com/assets/21009189/26756350/fb5cc4c6-48bd-11e7-9e41-beaf5a9f6947.jpg)
![screenshot_2017-06-03-19-22-38](https://cloud.githubusercontent.com/assets/21009189/26756349/fb5cf0a4-48bd-11e7-8773-12cae0bd65ad.jpg)

**Comment by nileshchat** [comment]
@Monal5031 So the issue here is you are not able to deactivate 'a' here?

**Comment by Monal5031** [comment]
@Nilesh4145 No. There were two `a` in the board when I used the first one (image1), the `b` was deactivated while when I used the second `a` b didn't get deactivated (image2).

**Comment by nileshchat** [comment]
@Monal5031 are you aware that only adjacent letters can be selected for making the word? Like in 1st image if you tap on 'a' the only options now you have are 'e', 'n', 'e', 'h', 'r' to choose from to make a word!!

**Comment by Monal5031** [comment]
@Nilesh4145 There is no mention about this thing in instructions, it should be mentioned I think. 😄

**Comment by nileshchat** [comment]
Yes, I agree, but does that resolve your issue @Monal5031 ?

**Comment by Monal5031** [comment]
@Nilesh4145 Yes my issue was that I was unable to choose any letter from board, which I think is resolved after this. Thanks 😄

**Comment by aviaryan** [comment]
@Nilesh4145 Thanks for clearing this up. Would you like to send a PR for this @Monal5031 ? We can have it in the instructions dialog .

**Comment by Monal5031** [comment]
Okay I'll send a PR. @aviaryan sir
