### ISSUE TITLE
Add screenshots in README

### ISSUE THREAD

**Issue by aviaryan** [aviaryan/Hinix#9]
Add gameplay screenshots to README under the header "Screenshots"

**[Important] Screenshots should not be stored in the repo. Use an external service for that.**

**Comment by hndr91** [comment]
Can I take this ?

**Comment by aviaryan** [comment]
@hndr91 Hey. Thanks for your interest. Yes you can take it. :) I will unassign @saurabhjn76

**Comment by raj-subhankar** [comment]
I can do it

**Comment by hndr91** [comment]
whoaa, I'm not so fast

**Comment by aviaryan** [comment]
@hndr91 :laughing: :laughing: All hail Hacktoberfest !
